### ISSUE TITLE
.collections.get_full_list() error

### ISSUE THREAD

**Issue by mc92mc** [vaphes/pocketbase#80] opened 2024-01-28 14:44 UTC
admin.collections.get_full_list()

  File "...\pocketbase\models\collection.py", line 37, in load
    self.schema.append(SchemaField(**field))
                       ^^^^^^^^^^^^^^^^^^^^
TypeError: SchemaField.__init__() got an unexpected keyword argument 'presentable'

```
@dataclass
class SchemaField:
    id: str = ""
    name: str = ""
    type: str = "text"
    system: bool = False
    required: bool = False
    presentable: bool = False
    unique: bool = False
    options: dict = field(default_factory=dict)
 ```
 add pls
 presentable: bool = False
thx =)

**Comment by m29h** [comment] 2024-01-28 16:06
This is an duplicate of #68 that was fixed in pull request #67
Are you running the latest version?

**Comment by m29h** [comment] 2024-01-28 16:14
@vaphes can you please make a new release? While the underlying pull request was merged 4months ago, the latest release on pypi that most people use is based on code from 5 months ago.

There are also a couple of other PR's that await merging...

**Comment by vaphes** [comment] 2024-02-08 13:32
done.

**Closed by vaphes** 2024-02-08 13:32 UTC
